name: golang-ci

on:
  pull_request:
    paths:
      - "services/golang/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/golang
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: 'services/golang/go.sum'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -coverprofile=c.out

      - uses: checkity/upload@v1
        with:
          file-pattern: '**/c.out'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          base-enabled: false # Only check overall coverage > 80%

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: andyyaldoo/pintu:golang
