name: nodejs

on:
  pull_request:
    paths:
      - "services/nodejs/**"
      - "deploy/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/nodejs
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/nodejs
          file: ./services/nodejs/deploy/Dockerfile
          push: true
          # TODO: add short commit hash?
          tags: andyyaldoo/pintu:nodejs

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: helm deploy
        working-directory: deploy/helm/http
        run: helm upgrade --install --create-namespace --atomic -f nodejs-values.yaml --namespace pintu nodejs . --debug --timeout 60s

      - name: Test service URLs
        run: |
          minikube service list
          minikube service node-http -n pintu --url
          echo  "------------------testing the service------------------"
          echo "/" && curl -s $(minikube service golang-http -npintu --url)/
