name: nodejs

on:
  pull_request:
    paths:
      - "services/nodejs/**"
      - "deploy/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/nodejs
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache dependency
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm install

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/nodejs
          file: ./services/nodejs/deploy/Dockerfile
          push: true
          tags: andyyaldoo/pintu:nodejs

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Check system pods are running
        run: kubectl get pods -A

      - name: Deploy service to k8s cluster
        working-directory: deploy/helm/http
        run: helm upgrade --install --create-namespace --atomic -f nodejs-values.yaml --namespace pintu nodejs . --debug --timeout 60s

      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-http -n pintu --url
          echo  "------------------testing the service------------------"
          echo "/" && curl -s $(minikube service nodejs-http -npintu --url)/
